background_file = 'img/background.png'
sodier_able_file = 'img/sodier_able.png'
archer_able_file = 'img/archer_able.png'
rider_able_file = 'img/rider_able.png'
sodier_unable_file = 'img/sodier_unable.png'
archer_unable_file = 'img/archer_unable.png'
rider_unable_file = 'img/rider_unable.png'
defeat_file="img/defeat.png"
victory_file="img/victory.png"
ally_tower_file = 'img/ally_tower.png'
enemy_tower_file = 'img/enemy_tower.png'
soliderA="img/ally_sodier.png"
riderA="img/ally_rider.png"
archerA="img/ally_archer.png"
soliderE="img/enemy_sodier.png"
riderE="img/enemy_rider.png"
archerE="img/enemy_archer.png"
first_point_file = 'img/first_point.png'
second_point_file = 'img/second_point.png'
third_point_file = 'img/third_point.png'
second_point_unable_file = 'img/second_point_unable.png'
third_point_unable_file = 'img/third_point_unable.png'
choiceLevel="img/choicelevel.png"
stronger="img/stronger.png"
quitgame="img/quitgame.png"
inputpage="img/input.png"
newgame="img/newgame.png"
continuep="img/continue.png"
